services:

  servall-db:
    image: postgres
    restart: on-failure:3
    container_name: evm-db
    ports:
      - "54321:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sa
    volumes:
      - evm-db-data:/var/lib/postgresql/data

volumes:
  evm-db-data: